ckeditor.plugin.uswds_grid:
  type: mapping
  label: 'CKEditor custom configuration'
  mapping:
    available_columns:
      type: sequence
      label: 'Allowed columns.'
    available_breakpoints:
      type: sequence
      label: 'Allowed Breakpoints.'

uswds_ckeditor_integration.settings:
  type: config_object
  mapping:
    breakpoints:
      type: sequence
      label: 'List of breakpoint configurations'
      sequence:
        type: mapping
        mapping:
          label:
            type: string
          prefix:
            type: string
          columns:
            type: sequence
