# Schema for the configuration files of the Mail Safety module.

mail_safety.settings:
  type: config_object
  label: 'Mail Safety settings'
  translatable: false
  mapping:
    enabled:
      type: boolean
      label: 'Enable the mail safety module to stop outgoing e-mails.'
    send_mail_to_dashboard:
      type: boolean
      label: 'Send the mails to the Mail Safety dashboard.'
    send_mail_to_default_mail:
      type: boolean
      label: 'Send the mails to the default mail address'
    default_mail_address:
      type: string
      label: 'The default mail address to send mails to that mail safety catches.'
