name: Creates Composer Container from upstream 

on:
  push:
    branches: [ container-build-composer ]
  pull_request:
    branches: [ container-build-composer ]

jobs:
  compose:
    name: Compose Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Pull Image
        #run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/
        run: docker pull natep18f/container-themebuild-test:container-build-composer
        
      - name: Copy workdir
        #run: docker cp $(docker create ${{ secrets.DOCKER_HUB_USERNAME }}/image:latest):/workdir www
        run: docker cp $(docker create ${{ secrets.DOCKER_HUB_USERNAME }}/container-themebuild-test:container-build-composer):/var/www theme

     # - name: Compress www folder
     #   run:  zip -r www.zip . -i www
      - name: Tar files
        run: tar -cvf theme.tar theme
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: theme
          path: theme.tar
        #with:
        #  name: www
        #  path: ${{ github.workspace }}/var/www/
 
