name: Builds theme container

on:
  push:
    branches: [ container-build-themebuild1 ]
  pull_request:
    branches: [ container-build-themebuild1 ]

jobs:  
  run-composer:
    name: Start container image
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@3

     - name: Start Container image
       run: docker run --name composer -d natep18f/container-themebuild-test:container-build-composer

     - name: Copy Work Dir
       run: |
         mkdir -p /tmp/artifact
         cp -r . /tmp/artifact
         cd /tmp/artifact
         zip -r artifact.zip .

     - name: Upload Artifact
       uses: actions/upload-artifact@v2
       with:
         name: artifact
         path: /tmp/artifact/artifact.zip
