name: Creates ThemeBuild Composer Container 

on:
  push:
    branches: [ container-build-themebuild ]
  pull_request:
    branches: [ container-build-themebuild ]

jobs:
  compose:
    name: Compose Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Run Image
        run: docker run --name composer natep18f/container-themebuild-test:container-build-composer 

      - name: Extract file from Docker container
        id: extract-file
        run: |
          mkdir theme
          docker cp composer:/var/www/web/themes theme
          cd theme
          ls
          docker cp composer:/var/www/web/libraries library
          docker rm composer
      #- name: Copy workdir
        #run: docker cp $(docker create ${{ secrets.DOCKER_HUB_USERNAME }}/container-themebuild-test:container-build-composer):/var/www/theme theme

      - name: Tar theme files
        run: |
          tar -cvf theme.tar theme
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: theme
          path: theme.tar

      - name: Tar library files
        run: |
          tar -cvf library.tar library
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: library.tar
          
  build-theme:
    needs: compose
    name: Builds themebuilder packages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download artifact
        uses: actions/download-artifact@v3
        id: library
        with:
          name: library
          path: library.tar
          
      - name: Download artifact
        uses: actions/download-artifact@v3
        id: theme
        with:
          name: theme
          path: theme.tar
          
      - name: 'Echo download path'
        run: |
          echo ${{steps.theme.outputs.download-path}} -l
          echo ${{steps.library.outputs.download-path}} -l
          
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            natep18f/container-themebuild-test
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false
  
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v2.5.0
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64
