name: Creates Composer Container from upstream 

on:
  push:
    branches: [ container-build-composer ]
  pull_request:
    branches: [ container-build-composer ]

jobs:
  build:
    name: Build Container Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: container:latest
          #labels: ${{ steps.meta.outputs.labels }}
          #platforms: linux/amd64, linux/arm64
          
      - name: Get container ID
        id: container
        run: echo "::set-output name=id::$(docker create image)"

      - name: copy workdir
        run: docker cp ${{ steps.container.outputs.id }}:/workdir .workdir

      - name: Remove Workdir
        run: docker rm ${{ steps.container.outputs.id }}

      - name: Zip
        run: zip -r workdir.zip workdir
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: composer-www-package
          path: workdir.zip
        
      #- name: Package Composer Output
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: composer-www-package
      #    path: /var/**/
      
      - name: Security scan
        uses: anchore/scan-action@v3
        with:
          image-reference: "ubuntu:latest"
          fail-build: true
