name: Run Composer Container, saves themes and library to artifacts then builds theme container

on:
  push:
    branches: [ container-build-themebuild ]
  pull_request:
    branches: [ container-build-themebuild ]

jobs:
  compose:
    name: Compose artifact creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Run Image
        run: |
          mkdir compose
          docker run --name composer natep18f/container-themebuild-test:container-build-composer 
          docker cp composer:/var/www/web compose
          ls -r compose

      - name: Tar compose files
        run: |
          tar -cvf compose.tar compose
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: compose
          path: compose.tar

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            natep18f/container-themebuild-test
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false
  
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v2.5.0
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64
