name: Creates Composer Container from upstream 

on:
  push:
    branches: [ container-build-composer ]
  pull_request:
    branches: [ container-build-composer ]

jobs:
  compose:
    name: Compose Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            natep18f/container-themebuild-test
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v2.5.0
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64

      - name: Pull Image
        #run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/
        run: docker pull natep18f/container-themebuild-test:container-build-composer
        
      - name: Copy workdir
        #run: docker cp $(docker create ${{ secrets.DOCKER_HUB_USERNAME }}/image:latest):/workdir www
        run: docker cp $(docker create ${{ secrets.DOCKER_HUB_USERNAME }}/container-themebuild-test:container-build-composer):/var/www www

     # - name: Compress www folder
     #   run:  zip -r www.zip . -i www
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        #with:
        #  name: www
        #  path: www.zip
        with:
          name: www
          path: ${{ github.workspace }}/var/www/
 
