name: Builds theme container

on:
  push:
    branches: [ container-build-themebuild1 ]
  pull_request:
    branches: [ container-build-themebuild1 ]

jobs:  
  run-composer:
    name: Start container image
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@3

     - name: Start Container image
       run: docker run -d --name composer -v ${{ github.workspace }}:/theme natep18f/container-themebuild-test:container-build-composer

     - name: Copy Work Dir
       run: docker cp . composer:/theme
       
     - name: Zip container folder
       run: docker exec composer zip -r release.zip /theme

     - name: Copy zip from container to host
       run: docker cp composer:/theme/release.zip
       
     - name: Upload Artifact
       uses: actions/upload-artifact@v2
       with:
         name: artifact
         path: release.zip
