name: Creates ThemeBuild Composer Container 

on:
  push:
    branches: [ container-build-themebuild ]
  pull_request:
    branches: [ container-build-themebuild ]

jobs:
  compose:
    name: Compose Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Run Image
        run: docker run --name composer natep18f/container-themebuild-test:container-build-composer 

      - name: Extract file from Docker container
        id: extract-file
        run: |
          mkdir theme
          docker cp composer:/var/www/web/themes theme
          cd theme
          ls
          docker rm composer
      #- name: Copy workdir
        #run: docker cp $(docker create ${{ secrets.DOCKER_HUB_USERNAME }}/container-themebuild-test:container-build-composer):/var/www/theme theme

      - name: Tar files
        run: tar -cvf theme.tar theme
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: theme
          path: theme.tar
