name: Buildx and upload artifact

# Triggers the workflow on push or pull request events
on:
  push:
    branches: [ container-build-composer ]
  pull_request:
    branches: [ container-build-composer ]

jobs:
  # This job uses docker buildx to build the image from the Dockerfile and uploads the WORKDIR as an artifact
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    name: Build Docker Images

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Builds the docker image using docker buildx and the Dockerfile in the repository
      - name: Build docker image
        run: docker buildx build --load -t my-image .

      # Gets the WORKDIR from the image
      - name: Get WORKDIR
        id: workdir
        run: echo "::set-output name=path::$(docker inspect --format='{{.Config.WorkingDir}}' my-image)"

      # Creates a temporary container from the image
      - name: Create container
        run: docker create --name my-container my-image

      # Copies the WORKDIR from the container to the host
      - name: Copy WORKDIR
        run: docker cp my-container:${{ steps.workdir.outputs.path }} ./workdir

      # Removes the temporary container
      - name: Remove container
        run: docker rm my-container

      # Zips the WORKDIR folder
      - name: Zip WORKDIR
        run: zip -r workdir.zip workdir

      # Uploads the zip file as an artifact for the workflow
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: workdir.zip
