name: Get and upload workdirs

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  # This job builds the docker image and gets the workdirs from it
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Builds the docker image using the Dockerfile in the repository
      - name: Build docker image
        run: docker build -t my-image .

      # Gets the list of workdirs from the image
      - name: Get workdirs
        id: workdirs
        run: echo "::set-output name=list::$(docker inspect --format='{{range .Config.WorkingDir}}{{.}} {{end}}' my-image)"

      # Loops through each workdir and copies it from the container to the host
      - name: Copy workdirs
        run: |
          for workdir in ${{ steps.workdirs.outputs.list }}; do
            docker cp my-container:$workdir ./workdir-$workdir
          done

      # Zips each workdir folder
      - name: Zip workdirs
        run: |
          for workdir in ${{ steps.workdirs.outputs.list }}; do
            zip -r workdir-$workdir.zip workdir-$workdir
          done

      # Uploads each zip file as an artifact for the workflow
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: |
            workdir-*.zip
